version: '3'

services:
  service1:
    build:
      context: ./service_1
    container_name: service1
    ports:
      - "8001:8001"

  service2:
    build:
      context: ./service_2
    container_name: service2
    ports:
      - "8002:8002"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - service1
      - service2
